#line 1 "./Ui/Form.tmpl"
#include "Content.h" 
#line 2 "./Ui/Form.tmpl"
namespace search_skin {
	#line 3 "./Ui/Form.tmpl"
	struct searchMessage :public cppcms::base_view
	#line 3 "./Ui/Form.tmpl"
	{
	#line 3 "./Ui/Form.tmpl"
		content::searchMessage &content;
	#line 3 "./Ui/Form.tmpl"
		searchMessage(std::ostream &_s,content::searchMessage &_content): cppcms::base_view(_s),content(_content)
	#line 3 "./Ui/Form.tmpl"
		{
	#line 3 "./Ui/Form.tmpl"
		}
		#line 4 "./Ui/Form.tmpl"
		virtual void render() {
			#line 199 "./Ui/Form.tmpl"
			out()<<"\n"
				"<!DOCTYPE html>\n"
				"<html>\n"
				"<head>\n"
				"  <title>Easearch</title>\n"
				"  <style type=\"text/css\">\n"
				"    html,body {\n"
				"      height: 100%;\n"
				"    }\n"
				"    body {\n"
				"      padding: 0;\n"
				"      margin: 0;\n"
				"      /*background: url(\"http://wallpapers.org.es/wp-content/uploads/2012/11/fondo-degradado-1024x640.jpg\");*/\n"
				"      background: url(\"http://imgstore.cdn.sogou.com/app/a/100540002/805168.jpg\");\n"
				"      background-position: center;\n"
				"      background-size: cover;\n"
				"      background-attachment: fixed;\n"
				"      background-repeat: no-repeat;\n"
				"    }\n"
				"    #title {\n"
				"      padding: 0;\n"
				"      margin: 0;\n"
				"      position: absolute;\n"
				"      -webkit-transform: translate(0, 0);\n"
				"      -moz-transform: translate(0, 0);\n"
				"      transform: translate(0, 0);\n"
				"      top: 30px;\n"
				"      left: 30px;\n"
				"      font-family: \"Futura\", Arial, Verdana;\n"
				"      font-size: 105px;\n"
				"      font-weight: lighter;\n"
				"      color: #FFF;\n"
				"    }\n"
				"    #intro {\n"
				"      padding: 0px;\n"
				"      margin: 0px;\n"
				"      width: 500px;\n"
				"      position: absolute;\n"
				"      top: 150px;\n"
				"      left: 260px;\n"
				"      font-family: \"Futura\", Arial, Verdana;\n"
				"      font-size: 28px;\n"
				"      font-weight: bold;\n"
				"      color: #FFF;\n"
				"    }\n"
				"    #input-holder {\n"
				"      height: 70px;\n"
				"      width: 550px;\n"
				"      padding:0px 80px 0 20px;\n"
				"      position: absolute;\n"
				"      top: 200px;\n"
				"      left: 35px;\n"
				"      background: rgba(0,0,0,0.5);\n"
				"      color: #FFF;\n"
				"      -webkit-box-sizing: border-box;\n"
				"      -moz-box-sizing: border-box;\n"
				"      box-sizing: border-box;\n"
				"      border-radius: 50px;\n"
				"      border: none;\n"
				"      outline: none;\n"
				"      font-family: \"Lucida Grande\", Arial, Verdana;\n"
				"      font-size: 20px;\n"
				"      font-weight: 400;\n"
				"      line-height: 20px;\n"
				"      -webkit-transition: all .3s cubic-bezier(0.000, 0.105, 0.035, 1.570);\n"
				"      -moz-transition: all .3s cubic-bezier(0.000, 0.105, 0.035, 1.570);\n"
				"      transition: all .3s cubic-bezier(0.000, 0.105, 0.035, 1.570);\n"
				"      -webkit-transition-delay: 0.3s;\n"
				"      -moz-transition-delay: 0.3s;\n"
				"      transition-delay: 0.3s;\n"
				"    }\n"
				"    #search {\n"
				"      width: 60px;\n"
				"      height: 60px;\n"
				"      margin: 10px;\n"
				"      border-radius: 30px;\n"
				"      border: none;\n"
				"      background: #FFF;\n"
				"      padding: 0px;\n"
				"      outline: none;\n"
				"      position: absolute;\n"
				"      font-family: \"Source Code Pro\", Arial, Verdana;\n"
				"      font-size: 35px;\n"
				"      font-weight: 400;\n"
				"      z-index: 2;\n"
				"      cursor: pointer;\n"
				"      color: #6600FF;\n"
				"      top: 195px;\n"
				"      left: 510px;\n"
				"      -webkit-transition: all 0.3s ease-in-out;\n"
				"      -moz-transition: all 0.3s ease-in-out;\n"
				"      transition: all 0.3s ease-in-out;\n"
				"    }\n"
				"    #result {\n"
				"      width: 850px;\n"
				"      word-wrap: break-word;\n"
				"      word-break: break-all;\n"
				"      padding: 18px 20px 20px 20px;\n"
				"      margin: 0 0 20px 0;\n"
				"      position: absolute;\n"
				"      top: 340px;\n"
				"      left: 35px;\n"
				"      background: rgba(0,0,0,0.5);\n"
				"      -webkit-box-sizing: border-box;\n"
				"      -moz-box-sizing: border-box;\n"
				"      box-sizing: border-box;\n"
				"      border-radius: 15px;\n"
				"      border: none;\n"
				"      outline: none;\n"
				"      font-family: \"Lucida Grande\", Arial, Verdana;\n"
				"      font-weight: 400;\n"
				"      -webkit-transition: all .3s cubic-bezier(0.000, 0.105, 0.035, 1.570);\n"
				"      -moz-transition: all .3s cubic-bezier(0.000, 0.105, 0.035, 1.570);\n"
				"      transition: all .3s cubic-bezier(0.000, 0.105, 0.035, 1.570);\n"
				"      -webkit-transition-delay: 0.3s;\n"
				"      -moz-transition-delay: 0.3s;\n"
				"      transition-delay: 0.3s;\n"
				"    }\n"
				"    #result_info {\n"
				"      position: absolute;\n"
				"      top: 268px;\n"
				"      left: 35px;\n"
				"      color: #FFF;\n"
				"      font-family: \"Lucida Grande\", Arial, Verdana;\n"
				"      font-size: 20px;\n"
				"      font-weight: bolder;\n"
				"      line-height: 40px;\n"
				"    }\n"
				"    #prev_page {\n"
				"      position: absolute;\n"
				"      top: 295px;\n"
				"      left: 25px;\n"
				"      width: 415px;\n"
				"      margin: 10px;\n"
				"      border-radius: 10px;\n"
				"      border: none;\n"
				"      background: #FFF;\n"
				"      padding: 0px 0px 6px 0px;\n"
				"      outline: none;\n"
				"      font-family: \"Lucida Grande\", Arial, Verdana;\n"
				"      font-size: 20px;\n"
				"      font-weight: 400;\n"
				"      z-index: 2;\n"
				"      cursor: pointer;\n"
				"      color: #6600FF;\n"
				"      -webkit-transition: all 0.3s ease-in-out;\n"
				"      -moz-transition: all 0.3s ease-in-out;\n"
				"      transition: all 0.3s ease-in-out;\n"
				"    }\n"
				"    #next_page {\n"
				"      position: absolute;\n"
				"      top: 295px;\n"
				"      left: 460px;\n"
				"      width: 415px;\n"
				"      margin: 10px;\n"
				"      border-radius: 10px;\n"
				"      border: none;\n"
				"      background: #FFF;\n"
				"      padding: 0px 0px 6px 0px;\n"
				"      outline: none;\n"
				"      font-family: \"Lucida Grande\", Arial, Verdana;\n"
				"      font-size: 20px;\n"
				"      font-weight: 400;\n"
				"      z-index: 2;\n"
				"      cursor: pointer;\n"
				"      color: #6600FF;\n"
				"      -webkit-transition: all 0.3s ease-in-out;\n"
				"      -moz-transition: all 0.3s ease-in-out;\n"
				"      transition: all 0.3s ease-in-out;\n"
				"    }\n"
				"    #r_title {\n"
				"      color: #FFF;\n"
				"      line-height: 55px;\n"
				"      font-size: 40px;\n"
				"    }\n"
				"    #r_abstr {\n"
				"      color: #999999;\n"
				"      line-height: 37px;\n"
				"      font-size: 20px;\n"
				"    }\n"
				"  </style>\n"
				"  <script type=\"text/javascript\">\n"
				"  function setPrompt() {\n"
				"    document.getElementById(\"input-holder\").placeholder = \"Type to search\";\n"
				"  }\n"
				"  function hidePageButton() {\n"
				"    document.getElementById(\"prev_page\").style.display = \"none\";\n"
				"    document.getElementById(\"next_page\").style.display = \"none\";\n"
				"  }\n"
				"  </script>\n"
				"</head>\n"
				"<body onload=\"setPrompt()\">\n"
				"<h1 id=\"title\">Easearch</h1>\n"
				"<h2 id=\"intro\"><strong>Easy-to-use search engine</strong></h2>\n"
				"<form method=\"POST\" action=\"\">\n"
				"";
			#line 199 "./Ui/Form.tmpl"
			{ cppcms::form_context _form_context(out(),cppcms::form_flags::as_html,cppcms::form_flags::as_space); (content.info).render(_form_context); }
			#line 201 "./Ui/Form.tmpl"
			out()<<"\n"
				"</form>\n"
				"<div id=\"result_info\">";
			#line 201 "./Ui/Form.tmpl"
			out()<<cppcms::filters::escape(content.result_info);
			#line 202 "./Ui/Form.tmpl"
			out()<<"</div>\n"
				"";
			#line 202 "./Ui/Form.tmpl"
			if(!(content.valid.empty())) {
				#line 204 "./Ui/Form.tmpl"
				out()<<"\n"
					"  <div id=\"result\">\n"
					"    <div id=\"r_title\">";
				#line 204 "./Ui/Form.tmpl"
				out()<<cppcms::filters::escape(content.result_0_title);
				#line 205 "./Ui/Form.tmpl"
				out()<<"</div>\n"
					"    <div id=\"r_abstr\">";
				#line 205 "./Ui/Form.tmpl"
				out()<<cppcms::filters::escape(content.result_0_abstr);
				#line 206 "./Ui/Form.tmpl"
				out()<<"</div><br><br>\n"
					"    <div id=\"r_title\">";
				#line 206 "./Ui/Form.tmpl"
				out()<<cppcms::filters::escape(content.result_1_title);
				#line 207 "./Ui/Form.tmpl"
				out()<<"</div>\n"
					"    <div id=\"r_abstr\">";
				#line 207 "./Ui/Form.tmpl"
				out()<<cppcms::filters::escape(content.result_1_abstr);
				#line 208 "./Ui/Form.tmpl"
				out()<<"</div><br><br>\n"
					"    <div id=\"r_title\">";
				#line 208 "./Ui/Form.tmpl"
				out()<<cppcms::filters::escape(content.result_2_title);
				#line 209 "./Ui/Form.tmpl"
				out()<<"</div>\n"
					"    <div id=\"r_abstr\">";
				#line 209 "./Ui/Form.tmpl"
				out()<<cppcms::filters::escape(content.result_2_abstr);
				#line 210 "./Ui/Form.tmpl"
				out()<<"</div><br><br>\n"
					"    <div id=\"r_title\">";
				#line 210 "./Ui/Form.tmpl"
				out()<<cppcms::filters::escape(content.result_3_title);
				#line 211 "./Ui/Form.tmpl"
				out()<<"</div>\n"
					"    <div id=\"r_abstr\">";
				#line 211 "./Ui/Form.tmpl"
				out()<<cppcms::filters::escape(content.result_3_abstr);
				#line 212 "./Ui/Form.tmpl"
				out()<<"</div><br><br>\n"
					"    <div id=\"r_title\">";
				#line 212 "./Ui/Form.tmpl"
				out()<<cppcms::filters::escape(content.result_4_title);
				#line 213 "./Ui/Form.tmpl"
				out()<<"</div>\n"
					"    <div id=\"r_abstr\">";
				#line 213 "./Ui/Form.tmpl"
				out()<<cppcms::filters::escape(content.result_4_abstr);
				#line 214 "./Ui/Form.tmpl"
				out()<<"</div><br><br>\n"
					"    <div id=\"r_title\">";
				#line 214 "./Ui/Form.tmpl"
				out()<<cppcms::filters::escape(content.result_5_title);
				#line 215 "./Ui/Form.tmpl"
				out()<<"</div>\n"
					"    <div id=\"r_abstr\">";
				#line 215 "./Ui/Form.tmpl"
				out()<<cppcms::filters::escape(content.result_5_abstr);
				#line 216 "./Ui/Form.tmpl"
				out()<<"</div><br><br>\n"
					"    <div id=\"r_title\">";
				#line 216 "./Ui/Form.tmpl"
				out()<<cppcms::filters::escape(content.result_6_title);
				#line 217 "./Ui/Form.tmpl"
				out()<<"</div>\n"
					"    <div id=\"r_abstr\">";
				#line 217 "./Ui/Form.tmpl"
				out()<<cppcms::filters::escape(content.result_6_abstr);
				#line 218 "./Ui/Form.tmpl"
				out()<<"</div><br><br>\n"
					"    <div id=\"r_title\">";
				#line 218 "./Ui/Form.tmpl"
				out()<<cppcms::filters::escape(content.result_7_title);
				#line 219 "./Ui/Form.tmpl"
				out()<<"</div>\n"
					"    <div id=\"r_abstr\">";
				#line 219 "./Ui/Form.tmpl"
				out()<<cppcms::filters::escape(content.result_7_abstr);
				#line 220 "./Ui/Form.tmpl"
				out()<<"</div><br><br>\n"
					"    <div id=\"r_title\">";
				#line 220 "./Ui/Form.tmpl"
				out()<<cppcms::filters::escape(content.result_8_title);
				#line 221 "./Ui/Form.tmpl"
				out()<<"</div>\n"
					"    <div id=\"r_abstr\">";
				#line 221 "./Ui/Form.tmpl"
				out()<<cppcms::filters::escape(content.result_8_abstr);
				#line 222 "./Ui/Form.tmpl"
				out()<<"</div><br><br>\n"
					"    <div id=\"r_title\">";
				#line 222 "./Ui/Form.tmpl"
				out()<<cppcms::filters::escape(content.result_9_title);
				#line 223 "./Ui/Form.tmpl"
				out()<<"</div>\n"
					"    <div id=\"r_abstr\">";
				#line 223 "./Ui/Form.tmpl"
				out()<<cppcms::filters::escape(content.result_9_abstr);
				#line 225 "./Ui/Form.tmpl"
				out()<<"</div>\n"
					"  </div>\n"
					"";
			#line 225 "./Ui/Form.tmpl"
			}else{
				#line 229 "./Ui/Form.tmpl"
				out()<<"\n"
					"  <script>\n"
					"    hidePageButton();\n"
					"  </script>\n"
					"";
			#line 229 "./Ui/Form.tmpl"
			}
			#line 232 "./Ui/Form.tmpl"
			out()<<"\n"
				"</body>\n"
				"</html>\n"
				"";
		#line 232 "./Ui/Form.tmpl"
		} // end of template render
	#line 233 "./Ui/Form.tmpl"
	}; // end of class searchMessage
#line 234 "./Ui/Form.tmpl"
} // end of namespace search_skin
#line 235 "./Ui/Form.tmpl"
namespace {
#line 235 "./Ui/Form.tmpl"
 cppcms::views::generator my_generator; 
#line 235 "./Ui/Form.tmpl"
 struct loader { 
#line 235 "./Ui/Form.tmpl"
  loader() { 
#line 235 "./Ui/Form.tmpl"
   my_generator.name("search_skin");
#line 235 "./Ui/Form.tmpl"
   my_generator.add_view<search_skin::searchMessage,content::searchMessage>("searchMessage",true);
#line 235 "./Ui/Form.tmpl"
    cppcms::views::pool::instance().add(my_generator);
#line 235 "./Ui/Form.tmpl"
 }
#line 235 "./Ui/Form.tmpl"
 ~loader() {  cppcms::views::pool::instance().remove(my_generator); }
#line 235 "./Ui/Form.tmpl"
} a_loader;
#line 235 "./Ui/Form.tmpl"
} // anon 
